# Generated by Django 4.2.6 on 2023-10-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_catergory_active_catergory_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
